name: "Greetings"
on: [issues, pull_request_target]  # pull_request

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Hi! thanks for your contribution!, great first issue!'
        pr-message: 'Hi! thanks for the input! Please give me a bit of time to review it!'
